language: python
sudo: false

cache: pip

python:
  - "3.4"
  - "2.7"

branches:
  only:
    - master

env:
 matrix:
  - DJANGO="django>=1.11,<1.12" DATABASE_URL='mysql://root@127.0.0.1/freeradius_test'
  - DJANGO="django>=1.11,<1.12" DATABASE_URL='postgres://postgres@127.0.0.1/freeradius_test'
  - DJANGO="django>=1.11,<1.12" DATABASE_URL='mysql://root@127.0.0.1/freeradius_test' SAMPLE_APP=1
  - DJANGO="django>=1.11,<1.12" DATABASE_URL='mysql://root@127.0.0.1/freeradius_test' SAMPLE_APP=1

before_install:
  - pip install --no-cache-dir -U -r requirements-test.txt
  - ./runflake8
  - ./runisort

install:
  - pip install $DJANGO
  - python setup.py -q develop

before_script:
  - ./runsphinx-build
  - if [ "$DATABASE_URL" == 'postgres://postgres@127.0.0.1/freeradius_test' ]; then psql -c "create database freeradius_test;" -U postgres; fi
  - if [ "$DATABASE_URL" == 'mysql://root@127.0.0.1/freeradius_test']; then mysql -e "create database IF NOT EXISTS freeradius_test;"; fi

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source=django_freeradius runtests.py

after_success:
  coveralls
